### ISSUE TITLE
Feature: Implement mouse controls

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/spirit-warrior#1]
## Tasks

- [x] Implement signal on mouse click and release
- [x] Character dash
  - [x] Compute slice power
  - [x] Apply slice power to character's inertia
- [x] Character power
  - [x] Compute power load
